service: integration-pipedrive-bling
app: integration-pipedrive-bling
org: vinholi

frameworkVersion: '2'
plugins: 
  - serverless-offline
  - serverless-offline-sns

custom:
  serverless-offline-sns:
    port: 4002
    debug: true

provider:
  name: aws
  runtime: nodejs12.x
  environment:
    DATABASE_URL: mongodb+srv://vinholi:admin@cluster.pgoev.mongodb.net/integration?retryWrites=true&w=majority
    ERP_URL: https://bling.com.br/Api/v2
    ERP_API_KEY: 038737d06529d72a376974ebe79bbdde3a1a8e492e7b288239112f500ce4819c5e474ad9

functions:
  get-orders:
    name: function-get-orders
    handler: src/use-cases/orders/get-orders.getOrders
    events:
      - http: 
          path: orders
          method: get
  order-orchestrator:
    name: function-order-orchestrator
    handler: src/use-cases/orders/order-orchestrator.orderOrchestrator
    events:
      - http:
          path: orders
          method: post
  create-order:
    name: function-create-order
    handler: src/use-cases/orders/create-order.createOrder
    events: 
      - sns: 
          arn: arn:aws:sns:us-east-1:123456789012:create-order
  update-order-status:
    name: function-update-order-status
    handler: src/use-cases/orders/update-order-status.updateOrderStatus
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:123456789012:update-order-status